







	



.build/uno/Wire/Wire.d : /usr/share/arduino/libraries/Wire/Wire.cpp
	@mkdir -p .build/uno/Wire
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial  -MM $^ > $@
	
	@printf ".build/uno/Wire/Wire.d .build/uno/Wire/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Wire/utility/twi.d : /usr/share/arduino/libraries/Wire/utility/twi.c
	@mkdir -p .build/uno/Wire/utility
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial  -MM $^ > $@
	
	@printf ".build/uno/Wire/utility/twi.d .build/uno/Wire/utility/" | cat - $@ > $@~ && mv $@~ $@



.build/uno/Wire/dependencies.d : .build/uno/Wire/Wire.d .build/uno/Wire/utility/twi.d
	@echo [96mScanning dependencies of Wire[0m
	@mkdir -p .build/uno/Wire
	@cat $^ > $@;

all : .build/uno/Wire/dependencies.d
	@true

